version: "3.2"
services:
  php: # PHP
    build:
      context: "./php/"
      args:
        PHP_VERSION: ${PHP_VERSION} # From .env
    networks:
      - backend
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/ # From .env
    container_name: php
  apache: # Server
    build:
      context: "./apache/"
      args:
        APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
    networks:
      - frontend
      - backend
    ports:
      - "${APACHE_PORT}:80"
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    container_name: apache
networks:
  frontend:
  backend:
volumes:
  data:
